version: "3.9"
services:
  collector-pc:
    image: ghcr.io/nanite-systems/stream-collector
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1000"
      - "9229:9229"
    networks:
      - "ps2alerts"
    environment:
      SERVICE_ID: "$CENSUS_SERVICE_ID"
      PS2_ENVIRONMENT: "ps2"
      RABBIT_URL: "amqp://guest:guest@ps2alerts-mq:5672"
    labels:
      traefik.enable: "false"

  collector-ps4eu:
    image: ghcr.io/nanite-systems/stream-collector
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1001"
    networks:
      - "ps2alerts"
    environment:
      SERVICE_ID: "$CENSUS_SERVICE_ID"
      PS2_ENVIRONMENT: "ps2ps4eu"
      RABBIT_URL: "amqp://guest:guest@ps2alerts-mq:5672"
    labels:
      traefik.enable: "false"

  collector-ps4us:
    image: ghcr.io/nanite-systems/stream-collector
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1002"
    networks:
      - "ps2alerts"
    environment:
      SERVICE_ID: "$CENSUS_SERVICE_ID"
      PS2_ENVIRONMENT: "ps2ps4us"
      RABBIT_URL: "amqp://guest:guest@ps2alerts-mq:5672"
    labels:
      traefik.enable: "false"
networks:
  ps2alerts:
    external:
      name: ps2alerts
