version: "3.9"
services:
  collector-pc:
    image: $VERSION
    restart: "no"
    volumes:
      - "../../:/app:rw"
    networks:
      - "ps2alerts"
    environment:
      SERVICE_ID: "$CENSUS_SERVICE_ID"
      PS2_ENVIRONMENT: "ps2"
      RABBITMQ_URL: "amqp://guest:guest@ps2alerts-mq:5672"
      RABBITMQ_COLLECTOR_EXCHANGE: "ps2alerts-census"
      SUBSCRIBE_EVENTS: "$CENSUS_EVENTS"
    labels:
      traefik.enable: "false"

  collector-ps4eu:
    image: "$VERSION"
    restart: "no"
    volumes:
      - "../../:/app:rw"
    networks:
      - "ps2alerts"
    environment:
      SERVICE_ID: "$CENSUS_SERVICE_ID"
      PS2_ENVIRONMENT: "ps2ps4eu"
      RABBITMQ_URL: "amqp://guest:guest@ps2alerts-mq:5672"
      RABBITMQ_COLLECTOR_EXCHANGE: "ps2alerts-census"
      SUBSCRIBE_EVENTS: "$CENSUS_EVENTS"
    labels:
      traefik.enable: "false"

  collector-ps4us:
    image: "$VERSION"
    restart: "no"
    volumes:
      - "../../:/app:rw"
    networks:
      - "ps2alerts"
    environment:
      SERVICE_ID: "$CENSUS_SERVICE_ID"
      PS2_ENVIRONMENT: "ps2ps4us"
      RABBITMQ_URL: "amqp://guest:guest@ps2alerts-mq:5672"
      RABBITMQ_COLLECTOR_EXCHANGE: "ps2alerts-census"
      SUBSCRIBE_EVENTS: "$CENSUS_EVENTS"
    labels:
      traefik.enable: "false"
networks:
  ps2alerts:
    external:
      name: ps2alerts
