---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
  vars_files:
    - ../../vars.local.yml
  tasks:
    - debug:
        msg: "========= 📡 Initializing Collector Module 📡 ========="

    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present

    - name: Install pika package to ensure devs can send messages to the queue
      pip:
        name: pika
        state: present

    - name: Create docker network
      docker_network:
        name: ps2alerts
        state: present
