---
- hosts: localhost
  tasks:
    - name: Stop any running docker-compose started modules
      docker_compose:
        project_src: .
        state: absent

    - name: Stop any running singular collector module
      docker_container:
        name: ps2alerts-collector-pc
        state: absent
