common:
  name: ps2alerts-collector

application:
  version: {{ version }}

deployments:
  one:
    index: "pc"
    containerImage: "ghcr.io/nanite-systems/stream-collector:1.0.0"
    env:
      - name: SERVICE_ID
        value: "${{ secrets.CENSUS_SERVICE_ID }}"
      - name: STREAM_ENDPOINT
        value: "wss://push.nanite-systems.net/streaming"
      - name: PS2_ENVIRONMENT
        value: "ps2"
      - name: RABBITMQ_URL
        value: "amqp://ps2alerts:${{ secrets.RABBITMQ_PS2ALERTS_PASS }}@ps2alerts-rabbitmq:5672/ps2alerts"
      - name: RABBITMQ_COLLECTOR_EXCHANGE_NAME
        value: "ps2alerts-census"
      - name: SUBSCRIBE_EVENTS
        value: "Death,FacilityControl,GainExperience,MetagameEvent,PlayerFacilityCapture,PlayerFacilityDefend,VehicleDestroy"
    nodeSelector:
      nodepool: perm-pool
  two:
    index: "ps4eu"
    containerImage: "ghcr.io/nanite-systems/stream-collector:1.0.0"
    env:
      - name: SERVICE_ID
        value: "${{ secrets.CENSUS_SERVICE_ID }}"
      - name: STREAM_ENDPOINT
        value: "wss://push.nanite-systems.net/streaming"
      - name: PS2_ENVIRONMENT
        value: "ps2ps4eu"
      - name: RABBITMQ_URL
        value: "amqp://ps2alerts:${{ secrets.RABBITMQ_PS2ALERTS_PASS }}@ps2alerts-rabbitmq:5672/ps2alerts"
      - name: RABBITMQ_COLLECTOR_EXCHANGE_NAME
        value: "ps2alerts-census"
      - name: SUBSCRIBE_EVENTS
        value: "Death,FacilityControl,GainExperience,MetagameEvent,PlayerFacilityCapture,PlayerFacilityDefend,VehicleDestroy"
    nodeSelector:
      nodepool: perm-pool
  three:
    index: "ps4us"
    containerImage: "ghcr.io/nanite-systems/stream-collector:1.0.0"
    env:
      - name: SERVICE_ID
        value: "${{ secrets.CENSUS_SERVICE_ID }}"
      - name: STREAM_ENDPOINT
        value: "wss://push.nanite-systems.net/streaming"
      - name: PS2_ENVIRONMENT
        value: "ps2ps4us"
      - name: RABBITMQ_URL
        value: "amqp://ps2alerts:${{ secrets.RABBITMQ_PS2ALERTS_PASS }}@ps2alerts-rabbitmq:5672/ps2alerts"
      - name: RABBITMQ_COLLECTOR_EXCHANGE_NAME
        value: "ps2alerts-census"
      - name: SUBSCRIBE_EVENTS
        value: "Death,FacilityControl,GainExperience,MetagameEvent,PlayerFacilityCapture,PlayerFacilityDefend,VehicleDestroy"
    nodeSelector:
      nodepool: perm-pool
