---
name: Build & Deploy Production
on:
  workflow_run:
    workflows: ["Tag & Release"]
    types:
      - completed
jobs:
  deploy-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: true

      - name: Get Latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 'UNKNOWN' # Optional fallback tag to use when no tag can be found

      # Copy the helm chart to the correct place for the below action to work
      - name: Move helm chart to correct position
        run: cp provisioning/helm/charts/microservice charts/app

      - name: Deploy PC
        uses: 'deliverybot/helm@v1'
        with:
          helm: helm3
          release: 'ps2alerts-collector'
          namespace: 'ps2alerts'
          chart: 'app'
          secrets: '${{ toJSON(secrets) }}'
          token: '${{ github.token}}'
          value-files: >-
          [
            "provisioning/production/values-pc.yaml",
          ]
          timeout: 300
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBE_CONFIG }}"

      # Outputs the rollout status and returns a 0 signal (thus completing the workflow) once it's rolled out.
      - uses: actions-hub/kubectl@master
        name: Wait for deployment to finish
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment/ps2alerts-aggregator-pc-production -n ps2alerts
