---
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
          submodules: true

      - name: Bump package version
        id: version
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'master'
          tag-prefix: 'v'

      - name: Create new GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.newTag }}

      - name: Find and replace version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{ version }}"
          replace: "${{ steps.version.outputs.newTag }}"
          include: provisioning/production/values.yaml

      - name: Deploy Helm
        uses: glopezep/helm@v1.8.0
        with:
          helm: helm3
          release: ps2alerts-collector
          namespace: ps2alerts
          chart: provisioning/helm/charts/microservice
          secrets: ${{ toJSON(secrets) }}
          token: ${{ github.token }}
          value-files: provisioning/production/values.yaml
          version: ${{ steps.version.outputs.newTag }}
          timeout: 120s
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBE_CONFIG_RAW }}"

      # Outputs the rollout status and returns a 0 signal (thus completing the workflow) once it's rolled out.
      - uses: actions-hub/kubectl@master
        name: Wait for deployment to finish
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment/ps2alerts-collector-pc -n ps2alerts
