# Bumps the version of the application
name: Tag & Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2

      - name: Bump package version
        id: version
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'master'
          tag-prefix: 'v'

      - name: Create new GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.newTag }}
